### ISSUE TITLE
Version of library web IDE does not support P1 module

### ISSUE THREAD

**Issue by apullin** [technobly/SparkCore-NeoPixel#20]
I am trying to build an example for a Sparkfun Photon Redboard, which I believe uses a P1 module.

When trying to build with the v0.0.7 of the library included all via the online IDE, I get the error:
```neopixel/neopixel.cpp:60:4: error: #error "*** PLATFORM_ID not supported by this library. PLATFORM should be Core or Photon ***"
#error "*** PLATFORM_ID not supported by this library. PLATFORM should be Core or Photon ***"```

**Comment by sasukenebe** [comment]
Hi, I also had this error, I was able to get it working with my photon redboard by commenting out all of the #if statements, or anything that referenced the PLATFORM_ID, let me know if that helps you get it working.

**Comment by apullin** [comment]
That doesn't help with the web IDE, as far as I know. Including the library just adds the #include into the .ino file, and the library CPP/H files aren't visible in the "project". The library code can be browsed by clicking through to the right place, but then not edited.
Maybe I am missing a piece of functionality in the Web IDE that will let me do the fix?

Is seems like all that would be needed is for the latest github version of the library to be published into the particle IDE ecosystem.

**Comment by sasukenebe** [comment]
Yeah, you need to fork it, then actually manually put the files in your project, and then edit them. Its kind of a pain but it worked for me, and these leds are so cool ^_^. let me know if that works.

**Comment by sasukenebe** [comment]
I took a moment to upload these slight edits to save you a few minutes of going through the library and editing out all the code, let me know if you get it working:
https://github.com/sasukenebe/Neopixel-Spark-Core-EDITED-for-Photon-Redboard

**Comment by technobly** [comment]
I just updated the neopixel library on Particle Build to v0.0.8, see release notes here:
https://community.particle.io/t/adafruit-neopixel-library-ported/1143/173

Closing for now, but please let me know if you are still having any trouble compiling for the Sparkfun P1 Redboard.  Thanks!
